### PR TITLE
Fix cluster name excessive sanitization when it is overridden.

### LINKED ISSUE #675: K8SSAND-1771 ⁃ K8ssandra is ignoring capital letters in the clusterName
**What happened?**
When trying to set the `clusterName` property with an uppercase letter, it will be ignored and continue to be used as a lowercase letter.

**Did you expect to see something different?**
The cluster_name inside `/etc/cassandra/cassandra.yaml` should contain the capital letter.

**How to reproduce it (as minimally and precisely as possible)**:

1. Set the following settings for k8ssandra: 
    ```yaml
    ...
    spec:
      cassandra:
        clusterName: "rikern-Cluster"
    ...
    ```
1. Compare the setting with `/etc/cassandra/cassandra.yaml`:
    ```bash
    # grep cluster_name /etc/cassandra/cassandra.yaml
    cluster_name: rikern-cluster
    ```

**Environment**

* K8ssandra Operator version:

    `1.2.0`
    
    * Kubernetes version information:

    ```
    Client Version: v1.25.0
    Kustomize Version: v4.5.7
    Server Version: v1.21.12
    ```
    * Kubernetes cluster kind:

   Rancher-Cluster

* Manifests:

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: rikern-cluster
spec:
  auth: false
  cassandra:
    clusterName: "rikern-Cluster"
    serverVersion: "3.11.12"
    resources:
      requests:
        memory: 4Gi
        cpu: 2
      limits:
        memory: 4Gi
        cpu: 2
    additionalSeeds: []
    racks:
      - name: eu-central-1a
    datacenters:
      - metadata:
          name: kubernetes-1
        size: 3
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: ebs
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
  reaper:
    autoScheduling:
      enabled: true
  stargate:
    size: 1
    heapSize: 4Gi
```

* K8ssandra Operator Logs:

```
1.6626517694445772e+09    INFO    controller.replicatedsecret    Starting reconciliation    {"reconciler group": "replication.k8ssandra.io", "reconciler kind": "ReplicatedSecret", "name": "rikern-cluster", "namespace": "jaschwege", "key": {"namespace": "jaschwege", "name": "rikern-cluster"}}
1.6626517694446528e+09    INFO    controller.k8ssandracluster    New initial system replication    {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "rikern-cluster", "namespace": "jaschwege", "K8ssandraCluster": "jaschwege/rikern-cluster", "SystemReplication": "{\"kubernetes-1\":3}"}
1.6626517694504676e+09    DEBUG    controller-runtime.webhook.webhooks    received request    {"webhook": "/validate-k8ssandra-io-v1alpha1-k8ssandracluster", "UID": "d182ee07-0c5c-4d65-9647-2a4232804f6f", "kind": "k8ssandra.io/v1alpha1, Kind=K8ssandraCluster", "resource": {"group":"k8ssandra.io","version":"v1alpha1","resource":"k8ssandraclusters"}}
1.6626517694509602e+09    INFO    k8ssandracluster-webhook    validate K8ssandraCluster update    {"K8ssandraCluster": "rikern-cluster"}
1.6626517694510016e+09    DEBUG    controller-runtime.webhook.webhooks    wrote response    {"webhook": "/validate-k8ssandra-io-v1alpha1-k8ssandracluster", "code": 200, "reason": "", "UID": "d182ee07-0c5c-4d65-9647-2a4232804f6f", "allowed": true}
1.6626517694581046e+09    INFO    controller.k8ssandracluster    Medusa reconcile for kubernetes-1 on namespace jaschwege    {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "rikern-cluster", "namespace": "jaschwege", "K8ssandraCluster": "jaschwege/rikern-cluster"}
1.6626517694581301e+09    INFO    controller.k8ssandracluster    Medusa is not enabled    {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "rikern-cluster", "namespace": "jaschwege", "K8ssandraCluster": "jaschwege/rikern-cluster"}
1.6626517694609392e+09    INFO    controller.replicatedsecret    Starting reconciliation    {"reconciler group": "replication.k8ssandra.io", "reconciler kind": "ReplicatedSecret", "name": "rikern-cluster", "namespace": "jaschwege", "key": {"namespace": "jaschwege", "name": "rikern-cluster"}}
1.6626517694646103e+09    INFO    controller.k8ssandracluster    Reconciling seeds    {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "rikern-cluster", "namespace": "jaschwege", "K8ssandraCluster": "jaschwege/rikern-cluster", "CassandraDatacenter": "jaschwege/kubernetes-1", "K8SContext": ""}
1.6626517694647381e+09    INFO    controller.k8ssandracluster    Waiting for datacenter to satisfy Ready condition    {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "rikern-cluster", "namespace": "jaschwege", "K8ssandraCluster": "jaschwege/rikern-cluster", "CassandraDatacenter": "jaschwege/kubernetes-1", "K8SContext": ""}
1.662651769475804e+09    INFO    controller.k8ssandracluster    updated k8ssandracluster status    {"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "rikern-cluster", "namespace": "jaschwege", "K8ssandraCluster": "jaschwege/rikern-cluster"}
```

**Anything else we need to know?**:

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1771) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1771
┆priority: Medium

### PR DESCRIPTION
**Pull request by adejanovski**
**What this PR does**:
Avoids sanitizing the cluster name when creating the cassdc, allowing the Cassandra cluster name to retain non k8s compliant characters.

**Which issue(s) this PR fixes**:
Fixes #675 

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [ ] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: apis/k8ssandra/v1alpha1/k8ssandracluster_types.go [hunk 1]
```diff
@@ -182,8 +182,14 @@ func (in *K8ssandraCluster) GetInitializedDatacenters() []CassandraDatacenterTem
 // SanitizedName returns a sanitized version of the Cassandra cluster name override if it exists,
 // otherwise the k8c object name.
 func (in *K8ssandraCluster) SanitizedName() string {
+	return cassdcapi.CleanupForKubernetes(in.CassClusterName())
+}
+
+// CassClusterName returns a sanitized version of the Cassandra cluster name override if it exists,
```
Comment (burmanm) [inline apis/k8ssandra/v1alpha1/k8ssandracluster_types.go:188]: I guess the comment is not quite accurate here ;)

File: controllers/k8ssandra/k8ssandracluster_controller_test.go [hunk 2]
```diff
@@ -297,6 +298,13 @@ func createSingleDcCluster(t *testing.T, ctx context.Context, f *framework.Frame
 		}
 		return false
 	}, timeout, interval)
+
+	// Check that the datacenter has the original cluster name, without sanitization.
+	// dc1 := cassdcapi.CassandraDatacenter{}
+	// err = f.Get(ctx, dcKey, &dc1)
+	// require.NoError(err, "failed to get CassandraDatacenter")
+	// require.Equal(kc.Spec.Cassandra.ClusterName, dc1.Spec.ClusterName)
```
Comment (burmanm) [inline controllers/k8ssandra/k8ssandracluster_controller_test.go:306]: Commented out?

Comment (burmanm) [reply controllers/k8ssandra/k8ssandracluster_controller_test.go:306]: Or just dead code and the later test is correct?

File: apis/k8ssandra/v1alpha1/k8ssandracluster_types.go (hunk 1 above)
Comment (adejanovski) [reply apis/k8ssandra/v1alpha1/k8ssandracluster_types.go:188]: No it's not 😬

File: controllers/k8ssandra/k8ssandracluster_controller_test.go (hunk 2 above)
Comment (adejanovski) [reply controllers/k8ssandra/k8ssandracluster_controller_test.go:306]: 🤦 
I commented it out while I was fixing some other related bugs.
Definitely need to get this uncommented to do the actual check on the cluster name that is passed to the cassdc object.

**Review by burmanm — APPROVED** [review]
