### PR TITLE
Fix invalid metrics names from MCAC and remove the localhost endpoint override from the new metrics agent

### LINKED ISSUE #925: Prometheus scrape errors: invalid metric name or label names
**What did you do?**

I deployed a K8ssandraCluster with Prometheus metrics enabled (see below) using the k8ssandra-operator.

Three of the four targets of the cass-servicemonitors throw scrape errors like this one:

```
invalid metric name or label names: {__name__="mcac_hints_hints_created.10.244.3.158.7000_total", cassandra_datastax_com_cluster="k8ssandra", cassandra_datastax_com_datacenter="dc1", cluster="k8ssandra", container="cassandra", dc="dc1", endpoint="prometheus", exported_instance="10.244.4.231", instance="10.244.4.231:9103", job="k8ssandra-dc1-all-pods-service", mcac="org.apache.cassandra.metrics.hints_service.hints_created.10.244.3.158.7000", mcac_filtered="true", namespace="cassandra", pod="k8ssandra-dc1-default-sts-0", rack="default", service="k8ssandra-dc1-all-pods-service"}
```

Is there something I can do about it? Is something wrong with my K8ssandraCluster?

**Did you expect to see some different?**

No scrape errors.

**Environment**

* K8ssandra Operator version:

    ```
    Image:         docker.io/k8ssandra/k8ssandra-operator:v1.6.0
    Image ID:      docker.io/k8ssandra/k8ssandra-operator@sha256:f74057380f4c18ea45c0c76f12e7eb74730209f232703cdfec5739514a16a4c3
    ```

* Kubernetes version information:

    ```yaml
    # kubectl version --output=yaml
    clientVersion:
      buildDate: "2023-03-15T13:37:18Z"
      compiler: gc
      gitCommit: ef70d260f3d036fc22b30538576bbf6b36329995
      gitTreeState: clean
      gitVersion: v1.24.12
      goVersion: go1.19.7
      major: "1"
      minor: "24"
      platform: linux/amd64
    kustomizeVersion: v4.5.4
    serverVersion:
      buildDate: "2023-03-15T13:30:13Z"
      compiler: gc
      gitCommit: ef70d260f3d036fc22b30538576bbf6b36329995
      gitTreeState: clean
      gitVersion: v1.24.12
      goVersion: go1.19.7
      major: "1"
      minor: "24"
      platform: linux/amd64
    ```

* Kubernetes cluster kind:

    bare metal, kubeadm

* Manifests:

    ```yaml
    apiVersion: k8ssandra.io/v1alpha1
    kind: K8ssandraCluster
    metadata:
      name: k8ssandra
    spec:
      auth: false
      cassandra:
        config:
          jvmOptions:
            heap_initial_size: 4G
            heap_max_size: 4G
        datacenters:
          - metadata:
              name: dc1
            resources:
              requests:
                cpu: 500m
                memory: 5Gi
              limits:
                cpu: 2
                memory: 10Gi
            size: 4
            storageConfig:
              cassandraDataVolumeClaimSpec:
                storageClassName: local-path
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
            telemetry:
              prometheus:
                commonLabels:
                  release: kube-prometheus-stack
                enabled: true
        serverVersion: "4.0.7"
      reaper:
        autoScheduling:
          enabled: true
        telemetry:
          prometheus:
            commonLabels:
              release: kube-prometheus-stack
            enabled: true
    ```

### PR DESCRIPTION
**Pull request by adejanovski**
**What this PR does**:
Fix relabeling issues with service monitors that didn't get the per node hints metrics names right (expecting a `-` instead of a `.`).
The last hint relabeling rule would also overwrite the previous ones due to the same issue.

The new metrics endpoint was configured to listen on localhost, which prevents scraping using the pod IP. The endpoint override was removed so that the metrics agent can listen on `0.0.0.0`.

**Which issue(s) this PR fixes**:
Fixes #925

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: pkg/telemetry/cassandra_agent/cassandra_agent_config.go [hunk 1]
```diff
@@ -25,8 +25,7 @@ var (
 	agentConfigLocation = "/opt/management-api/configs/metrics-collector.yaml"
 	defaultAgentConfig  = telemetryapi.CassandraAgentSpec{
 		Endpoint: &telemetryapi.Endpoint{
-			Port:    "9000",
-			Address: "127.0.0.1",
+			Port: "9000",
```
Comment (burmanm) [inline pkg/telemetry/cassandra_agent/cassandra_agent_config.go:28]: Do we even need this? It's port 9000 by default.

Comment (adejanovski) [reply pkg/telemetry/cassandra_agent/cassandra_agent_config.go]: ok, I've removed it 👍

**Comment by Miles-Garnsey** [comment]
> The new metrics endpoint was configured to listen on localhost, which prevents scraping using the pod IP. The endpoint override was removed so that the metrics agent can listen on 0.0.0.0.

Don't you want to scrape localhost given that vector running as a sidecar is doing the scraping? It isn't clear to me that this is a bad thing.

**Comment by adejanovski** [comment]
> > The new metrics endpoint was configured to listen on localhost, which prevents scraping using the pod IP. The endpoint override was removed so that the metrics agent can listen on 0.0.0.0.
> 
> Don't you want to scrape localhost given that vector running as a sidecar is doing the scraping? It isn't clear to me that this is a bad thing (esp from a security perspective) although I don't have a strong preference either way.

When using Vector it's fine indeed, the problem is that if scraping is done by Prometheus through a ServiceMonitor, then the pod ip will be used.

**Comment by burmanm** [comment]
> Don't you want to scrape localhost given that vector running as a sidecar is doing the scraping? It isn't clear to me that this is a bad thing (esp from a security perspective) although I don't have a strong preference either way.

Vector scraping is probably a very minor thing compared to using just Prometheus.
