### PR TITLE
Small secret controller fixes and updates [K8SSAND-851]

### LINKED ISSUE #103: concurrent map iteration and map write in secrets_controller.go
I was working on updating the integration tests for #102 and hit the following error on one test run:

```
time="2021-08-31T16:03:56-04:00" level=info msg="creating namespace" Context=cluster-0 Namespace=zz2z79k7g
time="2021-08-31T16:03:56-04:00" level=info msg="Starting EventSource" logger=controller-runtime.manager.controller.replicatedsecret reconciler group=k8ssandra.io reconciler kind=ReplicatedSecret source="{\"Type\":{\"metadata\":{\"creationTimestamp\":null},\"spec\":{},\"status\":{}}}"
time="2021-08-31T16:03:56-04:00" level=info msg="Starting EventSource" logger=controller-runtime.manager.controller.replicatedsecret reconciler group=k8ssandra.io reconciler kind=ReplicatedSecret source="{\"Type\":{\"metadata\":{\"creationTimestamp\":null}}}"
time="2021-08-31T16:03:56-04:00" level=info msg="Starting EventSource" logger=controller-runtime.manager.controller.replicatedsecret reconciler group=k8ssandra.io reconciler kind=ReplicatedSecret source="{}"
time="2021-08-31T16:03:56-04:00" level=info msg="Starting EventSource" logger=controller-runtime.manager.controller.replicatedsecret reconciler group=k8ssandra.io reconciler kind=ReplicatedSecret source="{}"
time="2021-08-31T16:03:56-04:00" level=info msg="Starting EventSource" logger=controller-runtime.manager.controller.replicatedsecret reconciler group=k8ssandra.io reconciler kind=ReplicatedSecret source="{}"
time="2021-08-31T16:03:56-04:00" level=info msg="Starting Controller" logger=controller-runtime.manager.controller.replicatedsecret reconciler group=k8ssandra.io reconciler kind=ReplicatedSecret
time="2021-08-31T16:03:56-04:00" level=info msg="creating namespace" Context=cluster-1 Namespace=zz2z79k7g
time="2021-08-31T16:03:56-04:00" level=info msg="creating namespace" Context=cluster-2 Namespace=zz2z79k7g
time="2021-08-31T16:03:57-04:00" level=info msg="Starting workers" logger=controller-runtime.manager.controller.replicatedsecret reconciler group=k8ssandra.io reconciler kind=ReplicatedSecret worker count=1
time="2021-08-31T16:04:07-04:00" level=info msg="creating namespace" Context=cluster-0 Namespace=jv7mqk55b
time="2021-08-31T16:04:07-04:00" level=info msg="creating namespace" Context=cluster-1 Namespace=jv7mqk55b
time="2021-08-31T16:04:07-04:00" level=info msg="creating namespace" Context=cluster-2 Namespace=jv7mqk55b
time="2021-08-31T16:04:07-04:00" level=info msg="Copying secret to target cluster" Secret=test-secret-first TargetContext="{\"k8sContextName\":\"cluster-1\"}" logger=controller-runtime.manager.controller.replicatedsecret name=fetch-secrets namespace=jv7mqk55b reconciler group=k8ssandra.io reconciler kind=ReplicatedSecret
fatal error: concurrent map iteration and map write

goroutine 6829 [running]:
runtime.throw(0x2866dca, 0x26)
	/usr/local/Cellar/go/1.16.4/libexec/src/runtime/panic.go:1117 +0x72 fp=0xc001bf78b0 sp=0xc001bf7880 pc=0x1039e32
runtime.mapiternext(0xc001bf79d8)
	/usr/local/Cellar/go/1.16.4/libexec/src/runtime/map.go:858 +0x54c fp=0xc001bf7930 sp=0xc001bf78b0 pc=0x1012a2c
runtime.mapiterinit(0x25fde60, 0xc000ae2000, 0xc001bf79d8)
	/usr/local/Cellar/go/1.16.4/libexec/src/runtime/map.go:848 +0x1c5 fp=0xc001bf7950 sp=0xc001bf7930 pc=0x10123e5
github.com/k8ssandra/k8ssandra-operator/controllers.(*SecretSyncController).SetupWithManager.func1(0x2b64e38, 0xc001bb3b80, 0xc001bf7ab0, 0xc001bf7c48, 0x1)
	/Users/johnsanda/Development/k8ssandra/k8ssandra-operator/controllers/secret_controller.go:326 +0x95 fp=0xc001bf7a48 sp=0xc001bf7950 pc=0x2494ab5
sigs.k8s.io/controller-runtime/pkg/handler.(*enqueueRequestsFromMapFunc).mapAndEnqueue(0xc0001947f0, 0x2b55708, 0xc0018a6640, 0x2b64e38, 0xc001bb3b80, 0xc001bf7b10)
	/Users/johnsanda/Development/gocode/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/handler/enqueue_mapped.go:80 +0x58 fp=0xc001bf7ae0 sp=0xc001bf7a48 pc=0x20ef158
sigs.k8s.io/controller-runtime/pkg/handler.(*enqueueRequestsFromMapFunc).Update(0xc0001947f0, 0x2b64e38, 0xc001bb3b80, 0x2b64e38, 0xc0005077c0, 0x2b55708, 0xc0018a6640)
	/Users/johnsanda/Development/gocode/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/handler/enqueue_mapped.go:63 +0xdb fp=0xc001bf7c60 sp=0xc001bf7ae0 pc=0x20eee7b
sigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnUpdate(0x2b41330, 0xc0001947f0, 0x2b55708, 0xc0018a6640, 0x0, 0x0, 0x0, 0x280d9e0, 0xc001bb3b80, 0x280d9e0, ...)
```

A single goroutine runs the reconcile function, but there is a separate (possible multiple) goroutine that handles event notifications. We need to either use a mutex or maybe sync.Map.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-851) by [Unito](https://www.unito.io)
┆Reviewer: 557058:376e6d8d-84b1-46a1-a227-0887055aa65a
┆Issue Number: K8SSAND-851
┆Priority: Medium

### PR DESCRIPTION
**Pull request by burmanm**
**What this PR does**:
Add tests for requiresUpdate (also modify, remove generational check and always calculate the hash of dest), syncSecrets, surround map changes with mutex. Also add GO_FLAGS to Makefile parameters

**Which issue(s) this PR fixes**:
Fixes #103

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by adutra** [comment]
The other controller tests were accidentally commented out:

https://github.com/k8ssandra/k8ssandra-operator/blob/main/controllers/controllers_test.go#L51-L56

Maybe you could re-enable them in this PR.

File: Makefile [hunk 1]
```diff
@@ -100,9 +101,9 @@ ENVTEST_ASSETS_DIR=$(shell pwd)/testbin
 test: manifests generate fmt vet envtest ## Run tests.
 ifdef TEST
 	@echo Running test $(TEST)
-	KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) -p path)" go test ./api/... ./pkg/... ./controllers/... -run="$(TEST)" -coverprofile cover.out
+	KUBEBUILDER_ASSETS="$(shell $(ENVTEST) use $(ENVTEST_K8S_VERSION) -p path)" go test $(GO_FLAGS) ./api/... ./pkg/... ./controllers/... -run="$(TEST)" -coverprofile cover.out
```
Comment (adutra) [inline Makefile:104]: What would be a typical usage of the `GO_FLAGS` variable? Shouldn't we add it to the `e2e-test` target too?

File: controllers/secret_controller.go [hunk 2]
```diff
@@ -42,7 +42,8 @@ const (
 type SecretSyncController struct {
 	ClientCache *clientcache.ClientCache
 	// TODO We need a better structure for empty selectors (match whole kind)
-	selectors map[types.NamespacedName]labels.Selector
+	selectorMutex sync.Mutex
```
Comment (adutra) [inline controllers/secret_controller.go:45]: A `sync.Mutex` must never be copied, and as such, should preferably be declared as a pointer `*sync.Mutex`.

File: Makefile (hunk 1 above)
Comment (burmanm) [reply Makefile:104]: Such as ``-v``

File: controllers/secret_controller.go (hunk 2 above)
Comment (burmanm) [reply controllers/secret_controller.go:45]: I disagree with this, ``sync.Mutex`` without the pointer is the format as recommended in Effective Go.

File: Makefile (hunk 1 above)
Comment (jsanda) [reply Makefile:104]: In #102 I added a `TEST_FLAGS` for suppressing the noisy output from kustomize and kubectl. See [here](https://github.com/k8ssandra/k8ssandra-operator/pull/102/commits/632d112951c8c08db39f9d00173543253ce7ca7d). I chose `TEST_FLAGS` vs `GO_FLAGS` it is intended for the test itself.

File: controllers/secret_controller.go (hunk 2 above)
Comment (jsanda) [reply controllers/secret_controller.go:45]: >sync.Mutex without the pointer is the format as recommended in Effective Go

Can you share a reference? And not just https://golang.org/doc/effective_go 😉

Comment (burmanm) [reply controllers/secret_controller.go:45]: https://golang.org/doc/effective_go#allocation_new ;)

Basically, it's because sync.Mutex valid state is zero-value, and thus everytime you create a struct of a pointer to struct, it works straight away: "The zero-value-is-useful property works transitively.". 

If it was *sync.Mutex, it wouldn't. As far as I can find, all instances of sync.Mutex in a struct are without pointer in Golang's source code: https://github.com/golang/go

File: Makefile (hunk 1 above)
Comment (burmanm) [reply Makefile:104]: That's TEST_ARGS ;). The GO_FLAGS was used in the k8ssandra, that's why I took the name.

File: controllers/secret_controller.go [hunk 3]
```diff
@@ -80,6 +81,9 @@ func (s *SecretSyncController) Reconcile(ctx context.Context, req ctrl.Request)
 
 				secretsToDelete := make([]*corev1.Secret, 0, len(secrets))
 
+				s.selectorMutex.Lock()
```
Comment (jsanda) [inline controllers/secret_controller.go:84]: This makes me nervous. We are holding the lock the entire time we iterate over secrets. While the number of secrets is probably going to be small in number, the actual number is arbitrary. We also perform deletes against the remote clusters in this loop. We have no idea what latencies could be like with those remote deletes. Any goroutine that tries to update the cache in the `toMatchingReplicates` function will be blocked. This may impact other controllers as well. What about making a copy of the cache here and using that in the loop?

File: controllers/secret_controller.go [hunk 4]
```diff
@@ -147,7 +151,9 @@ func (s *SecretSyncController) Reconcile(ctx context.Context, req ctrl.Request)
 	}
 
 	// Update the selector in cache always (comparing is pointless)
+	s.selectorMutex.Lock()
```
Comment (jsanda) [inline controllers/secret_controller.go:154]: I feel like we might be well served by defining a custom type for the selector cache and defining methods for accessing it. That would keep the concurrency aspect encapsulated and ensure reads and writes are done in a consistent fashion. wdyt?

File: controllers/secret_controller.go (hunk 3 above)
Comment (burmanm) [reply controllers/secret_controller.go:84]: I can modify this to use RWLock(), that shouldn't prevent adding new ones to the queue.

File: controllers/secret_controller.go (hunk 4 above)
Comment (burmanm) [reply controllers/secret_controller.go:157]: I think it would hide a pretty simple implementation unnecessarily.

File: controllers/secret_controller.go (hunk 3 above)
Comment (jsanda) [reply controllers/secret_controller.go]: Are you referring to a RWMutex? If so, isn't it still a mutually exclusive lock with respect to readers and writers?

Comment (burmanm) [reply controllers/secret_controller.go]: Yes, but we don't hold read lock for a long time (and don't do any calls to api-server while we hold it). 

Multiple readers can have the read lock at the same time, so they don't block each other.

Comment (jsanda) [reply controllers/secret_controller.go]: I realize that we don't hold the write lock for long and also that we can have multiple readers. My concern is that the loop could have the read lock for some time and block writes in `toMatchingReplicates`. Switching to a lock that allows multiple readers doesn't address this.

Comment (burmanm) [reply controllers/secret_controller.go]: toMatchingReplicas does not use write lock

Comment (jsanda) [reply controllers/secret_controller.go]: ah, I had to update my branch. I see the change. 👍

**Review by jsanda — CHANGES_REQUESTED** [review]
I think this PR is just about good to go. Looks like you need to update RBAC. e2e tests are failing with this error:

```
2021-09-08T02:21:46.845Z        INFO    setup   watch namespace configured      {"namespace": "single-dc-tb4nql"}
2021-09-08T02:21:47.548Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": ":8080"}
2021-09-08T02:21:48.346Z        ERROR   setup   unable to create controller     {"controller": "SecretSync", "error": "replicatedsecrets.k8ssandra.io is forbidden: User \"system:serviceaccount:single-dc-tb4nql:k8ssandra-operator\" cannot list resource \"replicatedsecrets\" in API group \"k8ssandra.io\" at the cluster scope"}main.main
```

**Review by jsanda — APPROVED** [review]
