### PR TITLE
Check and update system replication

### LINKED ISSUE #240: K8SSAND-1090 ⁃ Scaling the cluster causes a rolling restart
**What happened?**
When you scale a Cassandra cluster, either by adding nodes to a DC, removing nodes from a DC, or by adding a DC, it will trigger an unnecessary rolling restart for existing DCs. 

Replication of system keyspaces is configured by setting the following Java system properties in the `server-config-init` container:

* `cassandra.system_distributed_replication_dc_names`
* `cassandra.system_distributed_replication_per_dc`

They are specified in an env var that looks something like this:

```yaml
    - name: CONFIG_FILE_DATA
      value: '{"cluster-info":{"name":"test","seeds":"test-seed-service,test-dc1-additional-seed-service"},"datacenter-info":{"graph-
enabled":0,"name":"dc1","solr-enabled":0,"spark-enabled":0},"jvm-options":{"additional-jvm-opts":["-
Dcassandra.system_distributed_replication_dc_names=dc1","-Dcassandra.system_distributed_replication_per_dc=1"]}}'
```

This would be for a single node cluster. If we scale up our cluster to 2 nodes, k8ssandra-operator sets `cassandra.system_distributed_replication_per_dc=2`. This will cause a StatefulSet update, i.e., rolling restart, since it updates the underlying PodTemplateSpec.

What's worse is that if the scaling is within an existing DC, the replication doesn't get updated. The Java system properties are basically idempotent. Only their initial values are applied.

**Did you expect to see something different?**
The system keyspaces' replication should be configured as follows:

`replication = min(num_nodes, 3)`

Changing the replication should not trigger a rolling restart.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* K8ssandra Operator version:
1.0.0-alpha.2
* Manifests:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  cassandra:
    cluster: test
    serverVersion: "4.0.0"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      cassandraYaml:
        auto_snapshot: false
        memtable_flush_writers: 1
        commitlog_segment_size_in_mb: 2
        concurrent_compactors: 1
        compaction_throughput_mb_per_sec: 0
        sstable_preemptive_open_interval_in_mb: 0
        key_cache_size_in_mb: 0
        thrift_prepared_statements_cache_size_mb: 1
        prepared_statements_cache_size_mb: 1
        start_rpc: false
        slow_query_log_timeout_in_ms: 0
        counter_cache_size_in_mb: 0
        concurrent_reads: 2
        concurrent_writes: 2
        concurrent_counter_writes: 2
      jvmOptions:
        heapSize: 512Mi
    networking:
      hostNetwork: true
    resources:
      limits:
        memory: 1024Mi
    datacenters:
      - metadata:
          name: dc1
        size: 1
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1090) by [Unito](https://www.unito.io)
┆Reviewer: 557058:376e6d8d-84b1-46a1-a227-0887055aa65a
┆epic: Addition of new DataCenters
┆fixVersions: k8ssandra-operator-v1.0.0-alpha.3
┆friendlyId: K8SSAND-1090
┆priority: Medium

### PR DESCRIPTION
**Pull request by jsanda**
**What this PR does**:
* Store initial system replication in annotation on K8ssandraCluster
    * Done to help avoid rolling restart after a scaling event
* Check and update replication (if necessary) after each CassandraDatacenter becomes ready
    * Done in support of #21   

**Which issue(s) this PR fixes**:
Fixes #240

**Note:** I branches off of #233 for this PR, so it should be merged first, and then I will rebase as necessary.

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: controllers/k8ssandra/k8ssandracluster_controller_test.go [hunk 1]
```diff
@@ -1179,6 +1179,41 @@ func verifySuperUserSecretCreated(ctx context.Context, t *testing.T, f *framewor
...
+		actualReplication := &cassandra.SystemReplication{}
+		if err := json.Unmarshal([]byte(val), actualReplication); err != nil {
+			t.Logf("Failed to unmarshal system replication annotation: %v", err)
+			return false
+		}
+
+		return reflect.DeepEqual(expectedReplication, *actualReplication)
+	}, timeout, interval, "Failed to verify that the system replication annotation was set correctly")
+
+	kc = &api.K8ssandraCluster{}
```
Comment (adutra) [inline controllers/k8ssandra/k8ssandracluster_controller_test.go:1209]: Why retrieve the CRD again here?

File: controllers/k8ssandra/k8ssandracluster_controller.go [hunk 2]
```diff
@@ -197,239 +114,61 @@ func (r *K8ssandraClusterReconciler) reconcile(ctx context.Context, kc *api.K8ss
...
-			return ctrl.Result{RequeueAfter: r.ReconcilerConfig.LongDelay}, err
-		}
-	}
+	kcLogger.Info("Finished reconciling the k8ssandracluster")
 
-	// Reconcile Stargate and Reaper across all datacenters
+	return result.Done().Output()
+}
+
+func (r *K8ssandraClusterReconciler) reconcileStargateAndReaper(ctx context.Context, kc *api.K8ssandraCluster, dcs []*cassdcapi.CassandraDatacenter, logger logr.Logger) result.ReconcileResult {
```
Comment (adutra) [inline controllers/k8ssandra/k8ssandracluster_controller.go:156]: Maybe rename the method to something like `afterDatacentersFullyReconciled` since we are likely going to add more stuff here (Medusa, for instance).

File: controllers/k8ssandra/k8ssandracluster_controller.go [hunk 3]
```diff
@@ -602,21 +324,358 @@ func (r *K8ssandraClusterReconciler) setStatusForStargate(kc *api.K8ssandraClust
...
-func (r *K8ssandraClusterReconciler) reconcileStargateAuthSchema(
-	ctx context.Context,
-	kc *api.K8ssandraCluster,
-	dc *cassdcapi.CassandraDatacenter,
-	remoteClient client.Client,
-	logger logr.Logger,
-) error {
-	managementApi, err := r.ManagementApi.NewManagementApiFacade(ctx, dc, remoteClient, logger)
-	if err == nil {
+func (r *K8ssandraClusterReconciler) checkDeletion(ctx context.Context, kc *api.K8ssandraCluster, logger logr.Logger) result.ReconcileResult {
```
Comment (adutra) [inline controllers/k8ssandra/k8ssandracluster_controller.go:327]: How about moving this method + `checkFinalizer` to a separate file, to keep this one short and concise? 

(We would need to do the same for Stargate-related methods and methods related to secrets.)

File: controllers/k8ssandra/k8ssandracluster_controller.go [hunk 4]
```diff
@@ -602,21 +324,358 @@ func (r *K8ssandraClusterReconciler) setStatusForStargate(kc *api.K8ssandraClust
...
+
+func (r *K8ssandraClusterReconciler) reconcileReplicatedSecret(ctx context.Context, kc *api.K8ssandraCluster, logger logr.Logger) result.ReconcileResult {
+	if err := secret.ReconcileReplicatedSecret(ctx, r.Client, r.Scheme, kc, logger); err != nil {
+		logger.Error(err, "Failed to reconcile ReplicatedSecret")
+		return result.Error(err)
+	}
+	return result.Continue()
+}
+
+func (r *K8ssandraClusterReconciler) reconcileDatacenters(ctx context.Context, kc *api.K8ssandraCluster, logger logr.Logger) (result.ReconcileResult, []*cassdcapi.CassandraDatacenter) {
```
Comment (adutra) [inline controllers/k8ssandra/k8ssandracluster_controller.go:453]: And how about moving this one too, maybe to a `datacenters.go` file?

File: controllers/k8ssandra/k8ssandracluster_controller.go [hunk 5]
```diff
@@ -602,21 +324,358 @@ func (r *K8ssandraClusterReconciler) setStatusForStargate(kc *api.K8ssandraClust
...
+
+	return result.Continue(), actualDcs
+}
+
+// checkSystemReplication checks for the SystemReplicationAnnotation on kc. If found, the
+// JSON value is unmarshalled and returned. If not found, the SystemReplication is computed
+// and is stored in the SystemReplicationAnnotation on kc. The value is JSON-encoded.
+// Lastly, kc is patched so that the changes are persisted,
+func (r *K8ssandraClusterReconciler) checkSystemReplication(ctx context.Context, kc *api.K8ssandraCluster, logger logr.Logger) (*cassandra.SystemReplication, error) {
+	if val, found := kc.Annotations[api.SystemReplicationAnnotation]; found {
```
Comment (adutra) [inline controllers/k8ssandra/k8ssandracluster_controller.go:591]: Periodic reminder to use `utils.GetAnnotation` :-)

File: controllers/k8ssandra/k8ssandracluster_controller.go [hunk 6]
```diff
@@ -602,21 +324,358 @@ func (r *K8ssandraClusterReconciler) setStatusForStargate(kc *api.K8ssandraClust
...
+	}
+
+	return result.Continue(), actualDcs
+}
+
+// checkSystemReplication checks for the SystemReplicationAnnotation on kc. If found, the
+// JSON value is unmarshalled and returned. If not found, the SystemReplication is computed
+// and is stored in the SystemReplicationAnnotation on kc. The value is JSON-encoded.
+// Lastly, kc is patched so that the changes are persisted,
+func (r *K8ssandraClusterReconciler) checkSystemReplication(ctx context.Context, kc *api.K8ssandraCluster, logger logr.Logger) (*cassandra.SystemReplication, error) {
```
Comment (adutra) [inline controllers/k8ssandra/k8ssandracluster_controller.go:590]: And again, I'd move this method and the next one to a `replication.go` file, wdyt?

**Review by adutra — CHANGES_REQUESTED** [review]
@jdonenine and @jsanda I did a review round as requested, but it seems this PR needs some rebasing.

File: controllers/k8ssandra/k8ssandracluster_controller.go (hunk 2 above)
Comment (jsanda) [reply controllers/k8ssandra/k8ssandracluster_controller.go]: I'm good with renaming it, but Medusa stuff won't go there. The main parts for Medusa are deployed in the Cassandra pod.

Comment (jsanda) [reply controllers/k8ssandra/k8ssandracluster_controller.go]: The more I think about it I am not sure about the change. If I make that name change then `reconcileStargateAuthSchema` and `reconcileReaperSchema` should also be called in that method. Maybe that's fine. I suppose it would make it clear about where to put new method/function calls for later changes. @adutra wdyt?

Comment (adutra) [reply controllers/k8ssandra/k8ssandracluster_controller.go]: Indeed, schema reconciliation would have to happen inside this method. Since Medusa won't be involved here, I'd say let's leave the name as it is for now.

**Review by adutra — APPROVED** [review]

**Review by adutra — APPROVED** [review]
