### PR TITLE
Stargate fixes [K8SSAND-855]

### LINKED ISSUE #106: Check if data_endpoint_auth keyspace exists
**What is missing?**

See https://github.com/k8ssandra/k8ssandra-operator/pull/100#discussion_r700316041 for context.

The controller currently calls the `CreateKeyspace` endpoint for every Stargate resource tha it creates, in order to ensure that the `data_endpoint_auth` exists.
As a long-term solution, we are going to create a new Management API endpoint to list existing keyspaces.
Once this new endpoint is available, this PR would then change the controller code to call that endpoint first, and only call the `CreateKeyspace` endpoint if the `data_endpoint_auth` keyspace is not present yet.

**Why do we need it?**

In order to avoid issuing `CREATE KEYSPACE` statements for nothing.

**Environment**

Irrelevant

**Anything else we need to know?**:

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-855) by [Unito](https://www.unito.io)
┆Reviewer: 557058:376e6d8d-84b1-46a1-a227-0887055aa65a
┆Epic: Stargate Controller Integration
┆Fix Versions: k8ssandra-operator-1.0.0-alpha.1
┆Issue Number: K8SSAND-855
┆Priority: Medium

### PR DESCRIPTION
**Pull request by adejanovski**
**What this PR does**:
Check that the `data_endpoint_auth` keyspace exists before trying to create it during the reconcile loop.

We first need to have cass-operator released as 1.8.0-rc2 including support for the list keyspace operation from the management API, and upgrade the mgmt API to `-29` in order to get that PR working.

I was able to test the behavior locally: 

```
2021-09-16T12:49:12.087Z	INFO	The datacenter is ready	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "demo", "namespace": "default", "K8ssandraCluster": "default/demo", "CassandraDatacenter": "default/dc1"}
2021-09-16T12:49:12.189Z	INFO	Ensuring that keyspace data_endpoint_auth exists in cluster ...	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "demo", "namespace": "default", "K8ssandraCluster": "default/demo", "CassandraDatacenter": "default/dc1"}
2021-09-16T12:49:12.189Z	INFO	client::callNodeMgmtEndpoint	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "demo", "namespace": "default", "K8ssandraCluster": "default/demo", "CassandraDatacenter": "default/dc1"}
2021-09-16T12:49:12.198Z	INFO	client::callNodeMgmtEndpoint	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "demo", "namespace": "default", "K8ssandraCluster": "default/demo", "CassandraDatacenter": "default/dc1"}
2021-09-16T12:49:12.413Z	INFO	Keyspace data_endpoint_auth successfully created	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "demo", "namespace": "default", "K8ssandraCluster": "default/demo", "CassandraDatacenter": "default/dc1"}
2021-09-16T12:49:12.413Z	INFO	Creating Stargate resource	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "demo", "namespace": "default", "K8ssandraCluster": "default/demo", "CassandraDatacenter": "default/dc1", "Stargate": "default/demo-dc1-stargate"}
2021-09-16T12:49:12.432Z	INFO    Fetching Stargate resource	{"reconciler group": "k8ssandra.io", "reconciler kind": "Stargate", "name": "demo-dc1-stargate", "namespace": "default", "Stargate": {"namespace": "default", "name": "demo-dc1-stargate"}}
...
...
2021-09-16T12:49:27.485Z	INFO    Waiting for deployments to be rolled out	{"reconciler group": "k8ssandra.io", "reconciler kind": "Stargate", "name": "demo-dc1-stargate", "namespace": "default", "Stargate": {"namespace": "default", "name": "demo-dc1-stargate"}}
2021-09-16T12:49:27.486Z	INFO	The datacenter is ready	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "demo", "namespace": "default", "K8ssandraCluster": "default/demo", "CassandraDatacenter": "default/dc1"}
2021-09-16T12:49:27.486Z	INFO	Ensuring that keyspace data_endpoint_auth exists in cluster ...	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "demo", "namespace": "default", "K8ssandraCluster": "default/demo", "CassandraDatacenter": "default/dc1"}
2021-09-16T12:49:27.486Z	INFO	client::callNodeMgmtEndpoint	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "demo", "namespace": "default", "K8ssandraCluster": "default/demo", "CassandraDatacenter": "default/dc1"}
2021-09-16T12:49:27.573Z	INFO	Keyspace data_endpoint_auth already exists	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "demo", "namespace": "default", "K8ssandraCluster": "default/demo", "CassandraDatacenter": "default/dc1"}
2021-09-16T12:49:27.574Z	INFO	Waiting for Stargate to become ready	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "demo", "namespace": "default", "K8ssandraCluster": "default/demo", "CassandraDatacenter": "default/dc1", "Stargate": "default/demo-dc1-stargate"}
2021-09-16T12:49:27.673Z	INFO	updated k8ssandracluster status	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "demo", "namespace": "default", "K8ssandraCluster": "default/demo"}
```

In the above logs we can see that the KS is created and then on a subsequent iteration it's detected as already existing, which is the intended behavior.

**Which issue(s) this PR fixes**:
Fixes #106

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: controllers/k8ssandracluster_controller.go [hunk 1]
```diff
@@ -46,6 +46,10 @@ import (
 	"sigs.k8s.io/controller-runtime/pkg/source"
 )
 
+const (
+	STARGATE_AUTH_KEYSPACE = "data_endpoint_auth"
```
Comment (burmanm) [inline controllers/k8ssandracluster_controller.go:50]: This is Java naming convention. Use StargateAuthKeyspace or equal (if it needs to be exported, otherwise of course stargateAuthKeyspace).

File: controllers/k8ssandracluster_controller.go [hunk 2]
```diff
@@ -412,20 +416,30 @@ func (r *K8ssandraClusterReconciler) ensureStargateAuthKeyspaceExists(
...
+		if keyspaces, err := managementApi.ListKeyspaces(STARGATE_AUTH_KEYSPACE); err != nil {
+			return err
+		} else if len(keyspaces) == 0 {
+			// Stargate auth keyspace doesn't exist, we need to create it.
+			replication := make(map[string]int, len(kc.Spec.Cassandra.Datacenters))
+			for _, dcTemplate := range kc.Spec.Cassandra.Datacenters {
+				replicationFactor := int(math.Min(3.0, float64(dcTemplate.Size)))
+				replication[dcTemplate.Meta.Name] = replicationFactor
+			}
+			if err := managementApi.CreateKeyspaceIfNotExists("data_endpoint_auth", replication); err != nil {
```
Comment (burmanm) [inline controllers/k8ssandracluster_controller.go:432]: This line uses a magical string instead of the constant that was defined.

File: go.mod [hunk 3]
```diff
@@ -9,16 +9,16 @@ require (
...
-	github.com/k8ssandra/cass-operator v1.7.1
+	github.com/k8ssandra/cass-operator v1.8.0-rc2
 	github.com/pkg/errors v0.9.1
 	github.com/rs/zerolog v1.20.0
 	github.com/sirupsen/logrus v1.8.1
 	github.com/stretchr/testify v1.7.0
 	gopkg.in/resty.v1 v1.12.0
-	k8s.io/api v0.21.2
-	k8s.io/apimachinery v0.21.2
+	k8s.io/api v0.21.4
```
Comment (burmanm) [inline go.mod:18]: These values are overridden in the replace directive. Should be the same k8s version for everything.

File: test/kubectl/kubectl.go [hunk 4]
```diff
@@ -97,6 +98,9 @@ func DeleteByName(opts Options, kind, name string, ignoreNotFound bool) error {
 	if ignoreNotFound {
 		cmd.Args = append(cmd.Args, "--ignore-not-found")
 	}
+	var stdout, stderr bytes.Buffer
+	cmd.Stdout = &stdout
```
Comment (burmanm) [inline test/kubectl/kubectl.go:102]: Why?

File: controllers/k8ssandracluster_controller.go (hunk 1 above)
Comment (adejanovski) [reply controllers/k8ssandracluster_controller.go:50]: Right 😅

File: controllers/k8ssandracluster_controller.go (hunk 2 above)
Comment (adejanovski) [reply controllers/k8ssandracluster_controller.go:432]: I've lost some changes during a rebase it seems, good catch 👍

File: go.mod (hunk 3 above)
Comment (adejanovski) [reply go.mod:18]: I have no clue why/how these were changed 🤔

File: test/kubectl/kubectl.go (hunk 4 above)
Comment (adejanovski) [reply test/kubectl/kubectl.go:102]: Dunno 🤷 @adutra ?

File: controllers/k8ssandracluster_controller.go (hunk 1 above)
Comment (adejanovski) [reply controllers/k8ssandracluster_controller.go]: fixed

File: controllers/k8ssandracluster_controller.go (hunk 2 above)
Comment (adejanovski) [reply controllers/k8ssandracluster_controller.go]: fixed

File: go.mod (hunk 3 above)
Comment (adejanovski) [reply go.mod]: fixed

File: test/kubectl/kubectl.go (hunk 4 above)
Comment (burmanm) [reply test/kubectl/kubectl.go:102]: These will break the next CombinedOutput command for no reason (it sets those parameters and returns the result). Just remove these changes.

File: controllers/k8ssandracluster_controller.go [hunk 5]
```diff
@@ -215,23 +220,64 @@ func (r *K8ssandraClusterReconciler) reconcile(ctx context.Context, kc *api.K8ss
...
+			return ctrl.Result{}, err
 		}
-		result, err := r.reconcileStargate(ctx, kc, dcTemplate, actualDc, logger, remoteClient)
-		if !result.IsZero() || err != nil {
-			return result, err
+
+		desiredDcHash := utils.DeepHashString(desiredDc)
+		desiredDc.Annotations[api.ResourceHashAnnotation] = desiredDcHash
+
+		actualDc := &cassdcapi.CassandraDatacenter{}
```
Comment (adutra) [inline controllers/k8ssandracluster_controller.go:240]: I think it's a bit disappointing to re-fetch the actual DC here. It also might be slightly incorrect from the reconciliation logic perspective, because the DC specs could have been altered between the first fetch and the second one. I think it would be safer to store the actual DC in a slice:

```go
actualDcs := make([]*cassdcapi.CassandraDatacenter, 0, len(kc.Spec.Cassandra.Datacenters))
for i, dcTemplate := range kc.Spec.Cassandra.Datacenters {
    ...
    actualDcs[i] = actualDc
}
```

Then the reconcile loop for Stargate could be simplified:

```go
for i, dcTemplate := range kc.Spec.Cassandra.Datacenters {
	actualDc := actualDcs[i]
	dcKey := types.NamespacedName{Namespace: actualDc.Namespace, Name: actualDc.Name}
	logger := kcLogger.WithValues("CassandraDatacenter", dcKey)
	if remoteClient, err := r.buildRemoteClient(logger, dcTemplate, ctx, dcKey, actualDc, kc); err != nil {
		return ctrl.Result{}, err
	} else if result, err := r.reconcileStargate(ctx, kc, dcTemplate, actualDc, logger, remoteClient); !result.IsZero() || err != nil {
		return result, err
	}
}
```

File: controllers/k8ssandracluster_controller.go [hunk 6]
```diff
@@ -215,23 +220,64 @@ func (r *K8ssandraClusterReconciler) reconcile(ctx context.Context, kc *api.K8ss
...
+				return result, err
+			}
 		}
 	}
 
 	kcLogger.Info("Finished reconciling the k8ssandracluster")
 	return ctrl.Result{}, nil
 }
 
+func (r *K8ssandraClusterReconciler) buildRemoteClient(
```
Comment (adutra) [inline controllers/k8ssandracluster_controller.go:259]: The prefix "build" threw me off a bit since clients are cached. Maybe `retrieveRemoteClient`?

File: pkg/cassandra/management.go [hunk 7]
```diff
@@ -146,3 +155,41 @@ func (r *defaultManagementApiFacade) getCassandraContainerStatus(pod corev1.Pod)
...
+func (r *defaultManagementApiFacade) AlterKeyspace(
+	keyspaceName string,
+	replicationSettings map[string]int,
+) error {
+	if pods, err := r.fetchDatacenterPods(); err != nil {
+		r.logger.Error(err, "Failed to fetch datacenter pods")
+		return err
+	} else {
+		for _, pod := range pods {
+			if err := r.nodeMgmtClient.AlterKeyspace(&pod, keyspaceName, r.createReplicationConfig(replicationSettings)); err != nil {
```
Comment (adutra) [inline pkg/cassandra/management.go:186]: Just curious, what happens if the keyspace exists but was created with SimpleStrategy? Does the alter fail?

File: test/kubectl/kubectl.go (hunk 4 above)
Comment (adutra) [reply test/kubectl/kubectl.go:102]: I don't see the purpose of this change either. I think reverting is the right thing to do?

**Review by adutra — CHANGES_REQUESTED** [review]
Looking good, but I think the Stargate reconcile loop could be simplified.

One general remark: more than half of the files affected by this PR contained only reordered import statements. We need to tune our IDEs so that imports don't get re-ordered each time...

File: controllers/k8ssandracluster_controller.go [hunk 8]
```diff
@@ -215,23 +220,64 @@ func (r *K8ssandraClusterReconciler) reconcile(ctx context.Context, kc *api.K8ss
...
+	logger logr.Logger,
+	dcTemplate api.CassandraDatacenterTemplate,
+	ctx context.Context,
```
Comment (adutra) [inline controllers/k8ssandracluster_controller.go:262]: 4 unused parameters here.

File: controllers/k8ssandracluster_controller.go [hunk 9]
```diff
@@ -215,23 +220,64 @@ func (r *K8ssandraClusterReconciler) reconcile(ctx context.Context, kc *api.K8ss
...
+	dcKey types.NamespacedName,
+	actualDc *cassdcapi.CassandraDatacenter,
+	kc *api.K8ssandraCluster,
+) (client.Client, error) {
+	remoteClient, err := r.ClientCache.GetRemoteClient(dcTemplate.K8sContext)
```
Comment (adutra) [inline controllers/k8ssandracluster_controller.go:267]: Even better: I think we don't need the `buildRemoteClient` method at all: there are safety checks already in `r.ClientCache.GetRemoteClient`, and the custom error message created line 269 doesn't really bring any new information compared to the original error message.

File: pkg/cassandra/config.go [hunk 10]
```diff
@@ -110,6 +112,30 @@ func ApplySystemReplication(dcConfig *DatacenterConfig, replication SystemReplic
...
+			JvmOptions: &api.JvmOptions{},
+		}
+	} else if config.JvmOptions == nil {
+		config.JvmOptions = &api.JvmOptions{}
+	}
+
+	jvmOpts := config.JvmOptions
+	additionalOpts := jvmOpts.AdditionalOptions
+	if additionalOpts == nil {
+		additionalOpts = make([]string, 0, 2)
```
[the remark this answers is not in the document]
Comment (adejanovski) [reply pkg/cassandra/config.go:128]: good point 👍

File: pkg/cassandra/management.go (hunk 7 above)
Comment (adejanovski) [reply pkg/cassandra/management.go:186]: no it will succeed. You can alter SimpleStrategy to NTS, but it can generate some inconsistencies without a proper repair.

File: controllers/k8ssandracluster_controller.go (hunk 5 above)
Comment (adejanovski) [reply controllers/k8ssandracluster_controller.go:240]: I was thinking about this but wasn't sure about the lifecycle of these objects.
I'll give your solution a try to see how it works.

File: test/kubectl/kubectl.go (hunk 4 above)
Comment (adejanovski) [reply test/kubectl/kubectl.go:102]: I'll revert the changes

File: controllers/k8ssandracluster_controller.go [hunk 11]
```diff
@@ -118,12 +123,16 @@ func (r *K8ssandraClusterReconciler) reconcile(ctx context.Context, kc *api.K8ss
...
 	systemReplication := cassandra.ComputeSystemReplication(kc)
 
-	for i, dcTemplate := range kc.Spec.Cassandra.Datacenters {
+	for _, dcTemplate := range kc.Spec.Cassandra.Datacenters {
 		// Note that it is necessary to use a copy of the CassandraClusterTemplate because
 		// its fields are pointers, and without the copy we could end of with shared
 		// references that would lead to unexpected and incorrect values.
 		dcConfig := cassandra.Coalesce(kc.Spec.Cassandra.DeepCopy(), dcTemplate.DeepCopy())
 		cassandra.ApplySystemReplication(dcConfig, systemReplication)
+		if !strings.HasPrefix(dcConfig.ServerVersion, "3") && kc.HasStargates() {
```
Comment (adutra) [inline controllers/k8ssandracluster_controller.go:132]: There is a `isCassandra4(string)` function in the `cassandra` package FYI. That said, it currently returns true only for version = 4, while your test returns true for version >= 4. Maybe add a `isCassandra3(string)` function and use it in a negated form here?

File: controllers/k8ssandracluster_controller.go (hunk 9 above)
Comment (adejanovski) [reply controllers/k8ssandracluster_controller.go:267]: I'm all for less code 🙂 
I'll remove the function and use `r.ClientCache.GetRemoteClient` only in both loops.

File: controllers/k8ssandracluster_controller.go (hunk 6 above)
Comment (adejanovski) [reply controllers/k8ssandracluster_controller.go:259]: removing the function altogether based on your other comment.

File: controllers/k8ssandracluster_controller.go (hunk 11 above)
Comment (adejanovski) [reply controllers/k8ssandracluster_controller.go:134]: kk, doing this as well

**Review by adutra — APPROVED** [review]
