### PR TITLE
Fix for setting num_tokens

### LINKED ISSUE #530: K8SSAND-1468 ⁃ num_tokens cannot be set
Hi all!

I'm trying to deploy cassandra 3.11.7 cluster using the latest k8ssandra-operator. 
Setting the num_tokens value in the cassandra config won't do anything, but if I don't set that property the default (256) is set correctly and the cluster is deployed succesfully.

They way I'm setting the value:

imagen

I'm actually using k8ssandra-operator 1.0.2 and kubernetes v1.20.11.

I'm doing something wrong? or is it a bug? 

Thanks in advance!

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1468) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1468
┆priority: Medium

### PR DESCRIPTION
**Pull request by jeffbanks**
**What this PR does**:

Resolves issue reported as: `setting the num_tokens value in the Cassandra config won't do anything, but if I don't set that property the default (256) is set correctly and the cluster is deployed successfully.`

Identified as an equality check issue found in webhook validation logic.

Additional test coverage added along with fix to the update validation logic.

**Which issue(s) this PR fixes**:
Fixes #530 

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: apis/k8ssandra/v1alpha1/k8ssandracluster_webhook_test.go [hunk 1]
```diff
@@ -233,6 +233,54 @@ func testNumTokens(t *testing.T) {
 	cluster.Spec.Cassandra.CassandraConfig.CassandraYaml.NumTokens = nil
 	err = k8sClient.Update(ctx, cluster)
 	require.Error(err)
+
+	// Num_token update validations
```
Comment (jsanda) [inline apis/k8ssandra/v1alpha1/k8ssandracluster_webhook_test.go:237]: Looks like the scenario involved in the bug still isn't covered. That is, an update to the K8ssandraCluster other than num_tokens should not fail on num_tokens.

**Review by jsanda — CHANGES_REQUESTED** [review]
Looks like you need a rebase and have some small merge conflicts to resolve.

File: apis/k8ssandra/v1alpha1/k8ssandracluster_webhook_test.go (hunk 1 above)
Comment (jeffbanks) [reply apis/k8ssandra/v1alpha1/k8ssandracluster_webhook_test.go:244]: Good catch, I've updated w/ rebase to include that coverage in the latest push.
