### PR TITLE
fix logic for checking if rebuild task finished

### LINKED ISSUE #447: K8SSAND-1308 ⁃ Reconciliation never completes when adding a datacenter with more than one node
**What happened?**
I tried adding a DC to an existing CassandraDatacenter. The new DC was configured to have 3 C* nodes. Stargate and Reaper were enabled cluster-wide.  I observed the new CassandraDatacenter become ready, but neither Stargate nor Reaper were deployed. 

Upon investigation I discovered that this was due to a bug in how the operator is determining when a rebuild task completes.

**Did you expect to see something different?**
Stargate and Reaper should have been deployed, and reconciliation should have completed.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
  annotations:
spec:
  cassandra:
    serverVersion: "4.0.1"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      jvmOptions:
        heapSize: 512Mi
    datacenters:
      - metadata:
          name: dc1
        k8sContext: east
        size: 2
#      - metadata:
#          name: dc2
#       k8sContext: west
#        size: 2
  stargate:
    size: 1
    heapSize: 512Mi
    resources:
      limits:
        memory: 1024Mi
  reaper:
    autoScheduling:
      enabled: true
```

Create the K8ssandraCluster and wait for everything in the `east` cluster to become ready. Then uncomment `dc2` and apply the changes. The operator never finishes reconciling the rebuild task, and thus neither Stargate or Reaper get deployed in the `west` cluster.

**Environment**

* K8ssandra Operator version:

    `v1.0.0`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1308) by [Unito](https://www.unito.io)
┆Reviewer: 5fa4593062584c006b1e04d0
┆fixVersions: k8ssandra-operator-v1.0.1
┆friendlyId: K8SSAND-1308
┆priority: Medium

### PR DESCRIPTION
**Pull request by jsanda**
**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #447

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: controllers/k8ssandra/datacenters.go [hunk 1]
```diff
@@ -308,7 +308,7 @@ func (r *K8ssandraClusterReconciler) reconcileDcRebuild(
 	task := &cassctlapi.CassandraTask{}
 
 	if err := remoteClient.Get(ctx, taskKey, task); err == nil {
-		if taskFinished(task) {
+		if taskFinished(task, int(dc.Spec.Size)) {
```
Comment (burmanm) [inline controllers/k8ssandra/datacenters.go:311]: Will we end up in endless loop if I change the size before the rebuild has finished (but has started) ? Since we reconcile the size parameter before the rebuild checks.

Comment (jsanda) [reply controllers/k8ssandra/datacenters.go:311]: Indeed we would. If we add `dc2` with a size of 3 and then decide to change the size to 4 (in the K8ssandraCluster spec) after the rebuild job has started, we would get into an endless requeue loop. 

I'll store the number of nodes to be rebuilt in a label on the CassandraTask and then I can just check the value of that label.

**Review by burmanm — APPROVED** [review]
