### PR TITLE
Always set the cassandra.yaml jvm option for the Stargate pod

### LINKED ISSUE #683: K8SSAND-1782 ⁃ Stargate not working when using encryption
**What happened?**

Stargate is failing to start when i enable encryption in the Cassandra cluster.

**Did you expect to see something different?**

I expected to have a Stargate component working.

**How to reproduce it (as minimally and precisely as possible)**:

As easy as applying this manifest.

```
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: demo
spec:
  stargate:
    size: 1
  cassandra:
    serverEncryptionStores:
      keystoreSecretRef:
        name: demo-dc1-tls-keystore
      truststoreSecretRef:
        name: demo-dc1-tls-truststore
    clientEncryptionStores:
      keystoreSecretRef:
        name: demo-dc1-tls-keystore
      truststoreSecretRef:
        name: demo-dc1-tls-truststore
    serverVersion: "4.0.5"
    storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: gp3
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    config:
      jvmOptions:
        heapSize: 1024M
        additionalOptions:
        - -Djavax.net.debug=all
      cassandraYaml:
        server_encryption_options:
          internode_encryption: all
          require_client_auth: true
        client_encryption_options:
          enabled: true
          require_client_auth: true
    datacenters:
      - metadata:
          name: dc1
        size: 3
        racks:
        - name: eu-west-1a
          nodeAffinityLabels:
            topology.kubernetes.io/zone: eu-west-1a
        - name: eu-west-1b
          nodeAffinityLabels:
            topology.kubernetes.io/zone: eu-west-1b
        - name: eu-west-1c
          nodeAffinityLabels:
            topology.kubernetes.io/zone: eu-west-1c
```

**Environment**

* K8ssandra Operator version: 1.2.0
* Kubernetes version information:

```
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.11-eks-18ef993", GitCommit:"b9628d6d3867ffd84c704af0befd31c7451cdc37", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**:
After enabling `-Djavax.net.debug=all` i can see the following errors in the Cassandra nodes.

```
ERROR [Messaging-EventLoop-3-1] 2022-09-15 09:57:37,574 InboundConnectionInitiator.java:360 - Failed to properly handshake with peer /10.55.93.240:36094. Closing the channel.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1782) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1782
┆priority: Medium

### PR DESCRIPTION
**Pull request by adejanovski**
**What this PR does**:
The config map can be created by the operator itself in the case where encryption is turned on but no externally provided config map was present. In this case the jvm option wasn't added although it should have.
This resulted in Stargate failing to join the cluster when internode encryption is turned on, as it wouldn't get the encryption settings.

**Which issue(s) this PR fixes**:
Fixes #683

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by emerkle826 — APPROVED** [review]

File: pkg/stargate/deployments.go [hunk 1]
```diff
@@ -312,12 +312,11 @@ func computeJvmOptions(template *api.StargateTemplate) string {
...
-		jvmOptions += fmt.Sprintf(
-			" -Dstargate.unsafe.cassandra_config_path=%s",
-			cassandraConfigPath,
-		)
-	}
+	jvmOptions += fmt.Sprintf(
+		" -Dstargate.unsafe.cassandra_config_path=%s",
+		cassandraConfigPath,
+	)
+
```
Comment (olim7t) [inline pkg/stargate/deployments.go:319]: If I understand correctly, there is always a config (copied from the Cassandra one), even if the user did not provide their own?
Maybe it would be worth a quick explanation in a comment, with a reference to `stargate_controller.go`.

**Review by olim7t — APPROVED** [review]

File: pkg/stargate/deployments.go (hunk 1 above)
Comment (jsanda) [reply pkg/stargate/deployments.go:319]: There is always a ConfigMap which can be empty. We are only copying the `server_encryption_options` and `client_encryption_options` properties from Cassandra when they are set.

+1 to adding a comment.

Comment (jsanda) [reply pkg/stargate/deployments.go:319]: Should we add/update a test to verify that the JVM property is always set and that the ConfigMap is always created?

Comment (adejanovski) [reply pkg/stargate/deployments.go:319]: > Should we add/update a test to verify that the JVM property is always set and that the ConfigMap is always created?

I did so by modifying the single DC Stargate encryption test. It was passing before the fix because a `cassandra-config` config map was created before the K8ssandraCluster was created. Otherwise it would've been failing.
I've removed that config map to verify that the generated one would be passed on to Stargate correctly.

Comment (olim7t) [reply pkg/stargate/deployments.go:321]: > We are only copying the `server_encryption_options` and `client_encryption_options` properties from Cassandra when they are set.

That's very useful for #722, thanks.

File: config/crd/bases/config.k8ssandra.io_clientconfigs.yaml [hunk 2]
```diff
@@ -3,7 +3,7 @@ apiVersion: apiextensions.k8s.io/v1
 kind: CustomResourceDefinition
 metadata:
   annotations:
-    controller-gen.kubebuilder.io/version: v0.9.2
+    controller-gen.kubebuilder.io/version: v0.8.0
```
Comment (olim7t) [inline config/crd/bases/config.k8ssandra.io_clientconfigs.yaml:6]: What's the origin of this? The changes get reverted when I build locally.

Comment (adejanovski) [reply config/crd/bases/config.k8ssandra.io_clientconfigs.yaml:6]: It's because I'm using a version of controller-gen that's not the latest:

```
% controller-gen --version
Version: v0.8.0
```

no big deal.
