### PR TITLE
Fix the system schema replication annotation issue after 1.1 upgrade

### LINKED ISSUE #550: K8SSAND-1515 ⁃ Error when parsing the system replication annotation after v1.1.0 upgrade
**What happened?**
After upgrading to v1.1.0, the following error pops up in the operator logs:

```
1.652681134996166e+09	ERROR	controller.k8ssandracluster	System replication check failed	{"reconciler group": "k8ssandra.io", "reconciler kind": "K8ssandraCluster", "name": "dogfood", "namespace": "k8ssandra-operator", "K8ssandraCluster": "k8ssandra-operator/dogfood", "error": "json: cannot unmarshal array into Go value of type int"}
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).reconcile
	/workspace/controllers/k8ssandra/k8ssandracluster_controller.go:133
github.com/k8ssandra/k8ssandra-operator/controllers/k8ssandra.(*K8ssandraClusterReconciler).Reconcile
	/workspace/controllers/k8ssandra/k8ssandracluster_controller.go:87
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227
```

The code is trying to unmarshall the `initial-system-replication` annotation to a `map[string]int`, but the format we get from v1.0.0 is: `k8ssandra.io/initial-system-replication: '{"datacenters":["dc2","dc1"],"replicationFactor":3}'`

v1.1.0 rather expects the following format it seems: `{'dc1':3, 'dc2':3}`

We need to support both formats and migrate the old one to the new one during an upgrade.

**Did you expect to see something different?**
The upgrade shouldn't trigger any error and the operator should gracefully accept both formats, performing a silent migration to the new annotation format.

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade a cluster from v1.0.x to v1.1.0.

**Environment**
GKE

* K8ssandra Operator version:

    `v1.1.0`
    
    * Kubernetes cluster kind:

  GKE

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1515) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1515
┆priority: Medium

### PR DESCRIPTION
**Pull request by adejanovski**
**What this PR does**:
Implement a fix for errors when upgrading from v1.0 to v1.1.
The format of the `initial-system-replication` annotation has changed from `{"datacenters":["dc2","dc1"],"replicationFactor":3}` to `{'dc1':3, 'dc2':3}`, but the code only tries to parse the latter in v1.1.
This results in looping reconcile errors.

The fix identifies if the format is the old one, and if so lets the operator recompute the annotation and overwrite it.

This PR also adds an minimal e2e test that performs an upgrade from v1.0.0 to `latest` (which is the version built off 

**Which issue(s) this PR fixes**:
Fixes #550

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: controllers/k8ssandra/schemas.go [hunk 1]
```diff
@@ -117,7 +117,15 @@ func (r *K8ssandraClusterReconciler) checkInitialSystemReplication(
 		if err := json.Unmarshal([]byte(val), &replication); err == nil {
 			return replication, nil
 		} else {
-			return nil, err
+			// We could have an annotation in the old format. Try to parse it and convert it to the new format by pursuing the execution.
+			replicationOldFormat := make(map[string]interface{})
+			if err2 := json.Unmarshal([]byte(val), &replication); err2 == nil {
```
Comment (jsanda) [inline controllers/k8ssandra/schemas.go:122]: Shouldn't we be unmarshalling into `replicationOldFormat` here?

The old schema was:

```go
type SystemReplication struct {
	Datacenters       []string `json:"datacenters"`
	ReplicationFactor int      `json:"replicationFactor"`
}
```
Wouldn't it be better to make sure we marshal into the expected types? 

Lastly, if the old format is detected, should we convert it to the new format?

File: test/e2e/suite_test.go [hunk 2]
```diff
@@ -285,6 +286,11 @@ func TestOperator(t *testing.T) {
 			fixture:  framework.NewTestFixture("gc/4.0-jdk11-ZGC", controlPlane),
 		}))
 	})
+	t.Run("UpgradeTest", e2eTest(ctx, &e2eTestOpts{
```
[the remark this answers is not in the document]
Comment (adejanovski) [reply test/e2e/suite_test.go:289]: Sounds good 👍

File: config/deployments/default/kustomization.yaml [hunk 3]
```diff
@@ -8,5 +8,5 @@ resources:
 
 images:
   - name: k8ssandra/k8ssandra-operator
-    newTag: v1.1.0
+    newTag: v1.1.1-dev
```
[the remark this answers is not in the document]
Comment (adejanovski) [reply config/deployments/default/kustomization.yaml:11]: 👍

File: controllers/k8ssandra/schemas.go (hunk 1 above)
Comment (adejanovski) [reply controllers/k8ssandra/schemas.go:122]: > Shouldn't we be unmarshalling into replicationOldFormat here?

Good catch!

> Wouldn't it be better to make sure we marshal into the expected types?

Sure thing 👍 

> Lastly, if the old format is detected, should we convert it to the new format?

I think that's the right thing to do indeed.

**Review by jsanda — APPROVED** [review]
Even though there are test failures approving

File: controllers/k8ssandra/schemas.go [hunk 4]
```diff
@@ -112,16 +119,27 @@ func (r *K8ssandraClusterReconciler) checkInitialSystemReplication(
...
-			return nil, err
+			// We could have an annotation in the old format. Try to parse it and convert it to the new format by pursuing the execution.
+			var replicationOldFormat SystemReplicationOldFormat
+			if err2 := json.Unmarshal([]byte(val), &replicationOldFormat); err2 == nil {
+				replication = make(map[string]int)
+				for _, dc := range replicationOldFormat.Datacenters {
+					replication[dc] = replicationOldFormat.ReplicationFactor
+				}
+			} else {
+				logger.Error(err, "could not parse the inital-system-replication annotation of the K8ssandraCluster object")
```
Comment (burmanm) [inline controllers/k8ssandra/schemas.go:135]:
```suggestion
				logger.Error(err, "could not parse the initial-system-replication annotation of the K8ssandraCluster object")
```
