### PR TITLE
Fix/support non mandatory key file

### LINKED ISSUE #1152: Remove storageSecretRef requirement for Medusa - support AWS IAM Roles for Service Accounts (IRSA)
### Issue Description:

**What is missing?**
Currently, the configuration of Medusa within the K8ssandra Operator requires the use of `storageSecretRef` even though it is marked as optional. This is problematic for setups that utilize AWS IAM Roles for Service Accounts (IRSA) as it necessitates the provision of a `~/.aws/credentials` file to Medusa, which is not ideal or necessary when using IRSA.

**Why do we need it?**
To streamline the integration with AWS services and enhance security, we need the ability to configure Medusa to work with IRSA without the need for a `storageSecretRef`. This would allow Medusa to assume an IAM role and obtain temporary credentials directly from the AWS environment, eliminating the need to manage static credentials.

**Anything else we need to know?**:
This feature would greatly benefit users who are managing their Kubernetes clusters on AWS and are relying on the best practices for authentication by using IAM roles. It would also align with the AWS-recommended way of handling permissions for pods that require access to AWS resources.

### PR DESCRIPTION
**Pull request by JBOClara**
**What this PR does**:

While storageSecretRef is optional, there is no way to configure medusa without passing a secret. But when we want to use [role with IRSA ](https://docs.aws.amazon.com/fr_fr/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up-enable-IAM.html), we don't want to passe a `~/.aws/credentials` file to medusa.

 **Which issue(s) this PR fixes**: 
Fixes #1152
Fixes thelastpickle/cassandra-medusa#581

Linked to https://github.com/thelastpickle/cassandra-medusa/pull/691

**Checklist**
- [X] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -411,7 +411,7 @@ $(ENVTEST): $(LOCALBIN)
 	test -s $(LOCALBIN)/setup-envtest || GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
 
 OS=$(shell go env GOOS)
-ARCH=$(shell go env GOARCH)
+ARCH = amd64
```
Comment (JBOClara) [inline Makefile:414]:
```suggestion
ARCH=$(shell go env GOARCH)
```

File: controllers/k8ssandra/medusa_reconciler.go [hunk 2]
```diff
@@ -56,17 +59,23 @@ func (r *K8ssandraClusterReconciler) reconcileMedusa(
 
 		// Create required volumes for the Medusa containers
 		volumes := medusa.GenerateMedusaVolumes(dcConfig, medusaSpec, kc.SanitizedName())
+		logger.Info("Starting to create volumes for Medusa containers")
 		for _, volume := range volumes {
+			logger.Info("Created volume for Medusa container", "volume", volume.Volume.Name)
```
Comment (JBOClara) [inline controllers/k8ssandra/medusa_reconciler.go:64]:
```suggestion
```

File: controllers/k8ssandra/medusa_reconciler.go [hunk 3]
```diff
@@ -56,17 +59,23 @@ func (r *K8ssandraClusterReconciler) reconcileMedusa(
...
 			cassandra.AddOrUpdateVolume(dcConfig, volume.Volume, volume.VolumeIndex, volume.Exists)
 		}
+		logger.Info("Finished creating volumes for Medusa containers")
```
Comment (JBOClara) [inline controllers/k8ssandra/medusa_reconciler.go:67]:
```suggestion
```

File: controllers/k8ssandra/medusa_reconciler.go [hunk 4]
```diff
@@ -56,17 +59,23 @@ func (r *K8ssandraClusterReconciler) reconcileMedusa(
...
 
 		// Create the Medusa standalone pod
 		desiredMedusaStandalone := medusa.StandaloneMedusaDeployment(*medusaContainer, kc.SanitizedName(), dcConfig.SanitizedName(), namespace, logger)
 
 		// Add the volumes previously computed to the Medusa standalone pod
+		logger.Info("Starting to add volumes to the Medusa standalone pod")
```
Comment (JBOClara) [inline controllers/k8ssandra/medusa_reconciler.go:73]:
```suggestion
```

File: controllers/k8ssandra/medusa_reconciler.go [hunk 5]
```diff
@@ -56,17 +59,23 @@ func (r *K8ssandraClusterReconciler) reconcileMedusa(
...
 		for _, volume := range volumes {
+			logger.Info("Adding volume to the Medusa standalone pod", "volume", volume.Volume.Name)
```
Comment (JBOClara) [inline controllers/k8ssandra/medusa_reconciler.go:75]:
```suggestion
```

File: controllers/k8ssandra/medusa_reconciler.go [hunk 6]
```diff
@@ -56,17 +59,23 @@ func (r *K8ssandraClusterReconciler) reconcileMedusa(
...
 			cassandra.AddOrUpdateVolumeToSpec(&desiredMedusaStandalone.Spec.Template, volume.Volume, volume.VolumeIndex, volume.Exists)
 		}
+		logger.Info("Finished adding volumes to the Medusa standalone pod")
```
Comment (JBOClara) [inline controllers/k8ssandra/medusa_reconciler.go:78]:
```suggestion
```

File: controllers/k8ssandra/medusa_reconciler.go [hunk 7]
```diff
@@ -83,6 +92,7 @@ func (r *K8ssandraClusterReconciler) reconcileMedusa(
 		// Reconcile the Medusa standalone deployment
 		kcKey := utils.GetKey(kc)
 		desiredMedusaStandalone.SetLabels(labels.CleanedUpByLabels(kcKey))
+		logger.Info("Desired Medusa standalone deployment", "deployment", desiredMedusaStandalone)
```
Comment (JBOClara) [inline controllers/k8ssandra/medusa_reconciler.go:95]:
```suggestion
		logger.Debug("Desired Medusa standalone deployment", "deployment", desiredMedusaStandalone)
```

File: controllers/k8ssandra/medusa_reconciler.go [hunk 8]
```diff
@@ -83,6 +83,7 @@ func (r *K8ssandraClusterReconciler) reconcileMedusa(
 		// Reconcile the Medusa standalone deployment
 		kcKey := utils.GetKey(kc)
 		desiredMedusaStandalone.SetLabels(labels.CleanedUpByLabels(kcKey))
+		logger.Debug("Desired Medusa standalone deployment", "deployment", desiredMedusaStandalone)
```
Comment (laurentbardin) [inline controllers/k8ssandra/medusa_reconciler.go:86]:
```suggestion
		logger.Info("Desired Medusa standalone deployment", "deployment", desiredMedusaStandalone)
```

Comment (JBOClara) [reply controllers/k8ssandra/medusa_reconciler.go:86]:
```suggestion
```
I'll remove this since desiredMedusaStandalone is very big

**Review by laurentbardin — APPROVED** [review]
LGTM, but I know very little about Go and Cassandra so... 🤷

File: controllers/k8ssandra/medusa_reconciler.go [hunk 9]
```diff
@@ -41,7 +41,7 @@ func (r *K8ssandraClusterReconciler) reconcileMedusa(
 			}
 		}
 		if medusaSpec.StorageProperties.StorageSecretRef.Name == "" {
-			return result.Error(fmt.Errorf("medusa storage secret is not defined for storage provider %s", medusaSpec.StorageProperties.StorageProvider))
+			medusaSpec.StorageProperties.StorageSecretRef = corev1.LocalObjectReference{Name: ""}
```
[the remark this answers is not in the document]
Comment (JBOClara) [reply controllers/k8ssandra/medusa_reconciler.go:44]: I agree.

This could be a string field named CredentialsType with possible values like "role-based", "secret-based", etc.

**Comment by JBOClara** [comment]
Hello @adejanovski 
Could you give me a hint about this error https://github.com/k8ssandra/k8ssandra-operator/actions/runs/7120365184/job/19387445258?pr=1129#step:6:402 ?

I've no clue why is this failing.

**Comment by adejanovski** [comment]
I've restarted it, since we have some flakes on the K8ssandraTask tests. Let's see how it goes.

**Comment by adejanovski** [comment]
it passed ;)

**Comment by JBOClara** [comment]
Hello @adejanovski

Could you please review my PR and let me know if there's anything to add ? Are there any additional tests or documentation updates required to support this change?

Thank you for your guidance.

**Comment by yesterdays-vigilante** [comment]
This is blocking us at the moment as well - what's required to get this into the operator? Happy to help if I can.

**Comment by adejanovski** [comment]
> This is blocking us at the moment as well - what's required to get this into the operator? Happy to help if I can.

Hi @yesterdays-vigilante,

if you could test this PR and verify that the feature works as expected, it would be much appreciated.
I think it's going to need a rebase on top of main first to get the upgrade to the latest patch release of Medusa which supports role based auth.
@JBOClara, do you think you could rebase and force push?

**Comment by yesterdays-vigilante** [comment]
Hi @adejanovski! I've deployed this PR into our staging environment, and it seems to work alright - Medusa is able to put the backups in S3 using role-based authentication, and Cassandra still seems to be running fine.

If needed I can also rebase this branch on my own fork and make a new PR.

**Comment by adejanovski** [comment]
thanks a lot for the quick turnaround on testing this @yesterdays-vigilante 🙏 

Let's give @JBOClara a tiny bit of time to get back to this. That PR has been open for a while and I'm the one who dropped the ball on following up with it.

**Comment by adejanovski** [comment]
Hi @JBOClara, it looks like you still have a conflict on `go.sum`.

**Comment by adejanovski** [comment]
@JBOClara, for the unit tests to pass you'll need to regenerate the manifests I think (using `make manifests`) and commit the new CRDs before pushing again.

**Review by adejanovski — APPROVED** [review]
CI is green and everything looks good. Thanks @JBOClara !

**Comment by bradfordcp** [comment]
Thank you so much for working through this issue! I had worked around it in the past by providing an empty file via the referenced secret, but that always felt like a hack. Thanks again!

**Comment by c3-clement** [comment]
Hello @JBOClara , thank you so much for this change!
We were doing the same hack than @bradfordcp .

Is it also planned to support service account based auth for Google storage and workload identity based auth for Azure storage?

We have to implement similar hacks to those we used for S3 in order to support Google Cloud and Azure backups.

FYI @adejanovski

**Comment by JBOClara** [comment]
Hi @c3-clement,

I'm not able to test it on GCP or Azure.

But, did you already tried ? 

Unfortunately, I'm not planning to dedicate time to this topic.

**Comment by JamesXu2017** [comment]
> Thank you so much for working through this issue! I had worked around it in the past by providing an empty file via the referenced secret, but that always felt like a hack. Thanks again!

I tried the fake the secret, and using sa I created with S3 policay and role setup, I still not able to get around on this.  I am getting erros inside medusa-stanadalone
```botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity```
Any suggestion? @adejanovski

**Comment by JBOClara** [comment]
There is no need for a fake secret. Just use `role-based` as `credentialsType`.

Then, check this is correctly configured :

- Medusa runs with a specific k8s service account.
- This k8s sa is annotated with the IAM Role ARN annotation for IRSA.
- this IAM role has the permissions to write to the backup bucket
- this role has a trusted policy, that allows to assume role with web identity, with a condition based on the namespace and k8s SA name (see AWS Doc).
- your k8s cluster has a correctly configured IAM oidc provider https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up-enable-IAM.html
- this oidc provider is used in the trusted policy.

**Comment by adejanovski** [comment]
That's a great explanation that we'd need to put [in the docs](https://github.com/k8ssandra/k8ssandra-operator/blob/main/docs/content/en/tasks/backup-restore/_index.md) @JBOClara !

**Comment by c3-clement** [comment]
> Hi @c3-clement,
> 
> I'm not able to test it on GCP or Azure.
> 
> But, have you already tried? Could you share the errors encountered?
> 
> Unfortunately, I don't plan to dedicate time to this topic.

Hello @JBOClara,

Yes I already tried. I had to patch k8ssandra-operator and medusa - I don't have anymore error logs, but here is what went wrong:

Azure:

`medusa` was crashing at this line https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/storage/azure_storage.py#L48 because it's expects a `key` to be provided, which is not needed with Workload identity. Only the storage account name is needed.

Also, Azure Workload Identity auth requires to set the label `azure.workload.identity/use: "true"` to pods, and k8ssandra-operator does not propagate labels set in data centers to the medusa standalone deployment.


Google:

In the backup secret mounted to medusa pods, we have to set a field `credentials` with an arbitrary value, otherwise medusa will crash.

Also, in medusa codebase, the GCS list implementation is accessing unsafely the field `'md5Hash'` in the object returned by Google API
https://github.com/thelastpickle/cassandra-medusa/blob/master/medusa/storage/google_storage.py#L81

However, if the GCS bucket is KMS encrypted, the Google API does not expose the `'md5Hash'` field (I have talked with Google cloud support about this)
So if the bucket is KMS encrypted, Medusa will crash. We fixed it by using the `etag` field instead.


I will open proper GitHub issues for all of this when I got a sec.
I will also like to offer fixes for those issues I got time @JBOClara  @adejanovski

**Comment by c3-clement** [comment]
> > Thank you so much for working through this issue! I had worked around it in the past by providing an empty file via the referenced secret, but that always felt like a hack. Thanks again!
> 
> I tried the fake the secret, and using sa I created with S3 policay and role setup, I still not able to get around on this. I am getting erros inside medusa-stanadalone `botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity` Any suggestion? @adejanovski

I believe that the `serviceAccount` configured in datacenters is not propagated to the Medusa standalone deployment.
Could it be the cause of your issue @JamesXu2017 ?
FYI @JBOClara

**Comment by JBOClara** [comment]
Here is a PR https://github.com/k8ssandra/k8ssandra-operator/pull/1293 @adejanovski
